### ISSUE TITLE
Datastore batches distinguish between "" and None on delete_multi and throw

### ISSUE THREAD

**Issue by rwhogg** [googleapis/python-datastore#460] opened 2023-07-20 15:21 UTC
#### Environment details

  - OS type and version: Linux
  - Python version: 3.8.15
  - pip version: 23.2
  - `google-cloud-datastore` version:
```
Name: google-cloud-datastore
Version: 2.16.1
Summary: Google Cloud Datastore API client library
Home-page: https://github.com/googleapis/python-datastore
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /home/rwhogg/.pyenv/versions/3.8.15/lib/python3.8/site-packages
Requires: google-api-core, google-cloud-core, proto-plus, protobuf
Required-by: google-cloud-ndb
```

#### Steps to reproduce

  1. Get some keys with database == ""
  2. Get a datastore client with database of None
  3. Call `delete_multi` on those keys

#### Code example

```python
# batchbug.py
from google.cloud.datastore.client import Client

client = Client(project="myproject")

# Get some keys
query = client.query(kind="somekind")
query.keys_only()
for page in query.fetch().pages:
    keys = [entity.key for entity in page]

# Change the keys to have database == "".
# This isn't the normal way you would do this, it's just for reproducing the bug
keys = map(lambda k: k.__class__(
    *k.flat_path,
    project=k.project,
    database="",
    namespace=k.namespace
), keys)

# batch delete - throws error
client.delete_multi(keys)
```

#### Stack trace
```
Traceback (most recent call last):
  File "batchbug.py", line 18, in <module>
    client.delete_multi(keys)
  File "/home/rwhogg/.pyenv/versions/3.8.15/lib/python3.8/site-packages/google/cloud/datastore/client.py", line 721, in delete_multi
    current.delete(key)
  File "/home/rwhogg/.pyenv/versions/3.8.15/lib/python3.8/site-packages/google/cloud/datastore/batch.py", line 261, in delete
    raise ValueError("Key must be from same database as batch")
ValueError: Key must be from same database as batch
```

**Comment by daniel-sanche** [comment] 2024-07-10 22:54
This seems to be working as intended to me. "" and None mean different things in Python, so I would expect the library to distinguish between them

Specifically, when None is passed as the database ID, that tells the library to use the [the "(default)" database](https://github.com/googleapis/python-datastore/blob/7fd218b2afc0282d8fea21992e8d10c5eec72ac7/google/cloud/datastore/client.py#L185). An empty string would just refer to a database with [an invalid ID](https://cloud.google.com/datastore/docs/manage-databases#database_id), which I would expect to raise an error

I'm going to close this for now, but feel free to re-open if I'm missing something and this is adversely impacting you in some way

**Closed by daniel-sanche** 2024-07-10 22:54 UTC
Labels: type: bug, api: datastore, priority: p3
