### ISSUE TITLE
cannot delete entities via `client.delete_multi(keys)` due to missing `key.is_partial`

### ISSUE THREAD

**Issue by wescpy** [googleapis/python-datastore#118] opened 2020-11-23 06:23 UTC
#### Environment details

  - OS type and version: (irrelevant) Debian or Mac OS X
  - Python version: (whatever Python 3.8.x is installed for App Engine
  - pip version: (whatever pip version is installed for App Engine)
  - `google-cloud-datastore` version: 2.0.1
  - This bug is possibly related to </issues/106>
  - NOTE: the equivalent Cloud NDB call `ndb.delete_multi(keys)` doesn't have this issue 

#### Steps to reproduce

  1. create a bunch of Entities (mine were created w/a mixture of App Engine `ndb`, Cloud NDB, and Cloud Datastore APIs)
  1. try to delete a bunch of them with `client.delete_multi()` like the below

#### Code example

```python
@app.route('/trim', methods=['POST'])
def trim():
    '(push) task queue handler to delete oldest visits'
    oldest = float(request.get_json().get('oldest'))
    query = ds_client.query(kind='Visit')
    query.add_filter('timestamp', '<', datetime.fromtimestamp(oldest))
    query.keys_only()
    keys = list(query.fetch())
    nkeys = len(keys)
    if nkeys:
        print('Deleting %d entities: %s' % (
                nkeys, ', '.join(str(k.id) for k in keys)))
        ds_client.delete_multi(keys)
    return ''   # need to return SOME string w/the 200
```

#### Stack trace
```
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/layers/google.python.pip/pip/flask/_compat.py", line 39, in reraise
    raise value
  File "/layers/google.python.pip/pip/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/main.py", line 72, in trim
    ds_client.delete_multi(keys)
  File "/layers/google.python.pip/pip/google/cloud/datastore/client.py", line 674, in delete_multi
    current.delete(key)
  File "/layers/google.python.pip/pip/google/cloud/datastore/batch.py", line 215, in delete
    if key.is_partial:
AttributeError: 'Entity' object has no attribute 'is_partial'
```

#### Logging output (from `print()` in code snippet)
`Deleting 20 entities: 5634161670881280, 5644004762845184, 5632499082330112, 5642368648740864, 5636645067948032, 5646488461901824, 5631671361601536, 5700433016258560, 5704568633556992, 5638358357245952, 5714489739575296, 5635008819625984, 5665673409724416, 5701666712059904, 5643280054222848, 5712837116690432, 5675594515742720, 5673082664517632, 5679095853613056, 5710353417633792`

#### Logging request payload
```json
{
  "textPayload": "Deleting 20 entities: 5634161670881280, 5644004762845184, 5632499082330112, 5642368648740864, 5636645067948032, 5646488461901824, 5631671361601536, 5700433016258560, 5704568633556992, 5638358357245952, 5714489739575296, 5635008819625984, 5665673409724416, 5701666712059904, 5643280054222848, 5712837116690432, 5675594515742720, 5673082664517632, 5679095853613056, 5710353417633792",
  "insertId": "5fbb4dc70008d6d28f2d109c",
  "resource": {
    "type": "gae_app",
    "labels": {
      "zone": "us-west2-2",
      "project_id": "PROJECT_ID",
      "version_id": "20201122t214608",
      "module_id": "default"
    }
  },
  "timestamp": "2020-11-23T05:51:03.579282Z",
  "labels": {
    "clone_id": "00c61b117c75deebba7b27c504a499ddf8ea92b36598da2882bed3d2ef42424ec9111c5ba02e5f72a6e0fc8d080f4492ef10109b2f12d706a90fb49d7e7e58d8"
  },
  "logName": "projects/PROJECT_ID/logs/stdout",
  "receiveTimestamp": "2020-11-23T05:51:03.580567100Z"
}
```

#### Example Entity (the 1st one) the code tried to delete (`5634161670881280`)
![image](https://user-images.githubusercontent.com/1102504/99933845-0a928300-2d11-11eb-9dbe-c743560dbd76.png)

#### `app.yaml` file
```yml
runtime: python38

handlers:
- url: /.*
  script: auto
```
#### `requirements.txt` file
```
Flask==1.1.2
google-cloud-datastore==2.0.1
google-cloud-tasks==2.0.0
```

**Comment by crwilcox** [comment] 2020-11-25 22:56
`delete_multi` takes an array of keys, but as authored the type of `keys` is `datastore.Entity`

```
keys = list(query.fetch())
```

a more accurate name for this variable would be `entities`

```
entities = list(query.fetch())
```



```
query = client.query(kind='Task')
query.add_filter('description', '>', '0')
query.keys_only()
entities = list(query.fetch())
nkeys = len(entities)

if nkeys:
    print('Deleting %d entities: %s' % (
            nkeys, ', '.join(str(k.id) for k in entities)))
    client.delete_multi([i.key for i in entities])
```

**Comment by crwilcox** [comment] 2020-11-25 23:02
Did the code provided work at any point? Or is this more of a question? I have verified that for both 1.15.3 and 2.0.1 the code provided fails due to invalid types, but works if ran as I specify above. Hoping to confirm that you aren't seeing a regression before closing.

**Comment by crwilcox** [comment] 2020-11-25 23:27
Confirmed this isn't a regression. It is a confusion about that NDB changes return type when keys_only is specified. I have opened a bug against NDB to investigate docsting/typing.

I don't think we want to replicate the behavior as it would result in varying return types. We could possible add a query.fetch_keys() method that would be a thin-wrapper.

**Closed** 2020-11-25 23:28 UTC
Labels: :rotating_light:, api: datastore, priority: p0, type: bug
